NewsBoard/ViewModels/NewsViewModel.cs
using System.Collections.Generic;
using NewsBoard.Model;

namespace NewsBoard.Web.ViewModels
{
    public class NewsViewModel
    {
        public string Category { get; set; }

        public IEnumerable<string> Categories { get; set; }
        public IEnumerable<NewsSourceViewModel> NewsSources { get; set; }
        public bool HasFacebook { get; set; }
        public IEnumerable<FacebookPostsViewModel> FacebookPosts { get; set; }
        public string OdataEndpoint { get; set; }
    }


    public class NewsSourceViewModel
    {
        public NewsSource NewsSource { get; set; }
        public bool Ignored { get; set; }
    }
}

NewsBoard/Controllers/NewsCategoriesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using NewsBoard.Model;
using NewsBoard.Persistence;

namespace NewsBoard.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class NewsCategoriesController : Controller
    {
        private NewsDb db = new NewsDb();

        // GET: /NewsCategories/
        public ActionResult Index()
        {
            return View(db.NewsCategories.ToList());
        }

        // GET: /NewsCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsCategory newscategory = db.NewsCategories.Find(id);
            if (newscategory == null)
            {
                return HttpNotFound();
            }
            return View(newscategory);
        }

        // GET: /NewsCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /NewsCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] NewsCategory newscategory)
        {
            if (ModelState.IsValid)
            {
                db.NewsCategories.Add(newscategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newscategory);
        }

        // GET: /NewsCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsCategory newscategory = db.NewsCategories.Find(id);
            if (newscategory == null)
            {
                return HttpNotFound();
            }
            return View(newscategory);
        }

        // POST: /NewsCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] NewsCategory newscategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newscategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newscategory);
        }

        // GET: /NewsCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsCategory newscategory = db.NewsCategories.Find(id);
            if (newscategory == null)
            {
                return HttpNotFound();
            }
            return View(newscategory);
        }

        // POST: /NewsCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewsCategory newscategory = db.NewsCategories.Find(id);
            db.NewsCategories.Remove(newscategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

NewsBoard/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NewsBoard.Persistence;
using NewsBoard.Utils;
using NewsBoard.Web.Models;
using NewsBoard.Web.ViewModels;

namespace NewsBoard.Web.Controllers
{
    public class NewsController : Controller
    {
        public enum Order
        {
            NewestFirst,
            AToZ,
            ZToA
        }

        private NewsDb _db = new NewsDb();

        private UserManager<ApplicationUser> _manager =
            new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

        // GET: /News
        public ActionResult Index(string category, Order order = Order.NewestFirst)
        {
            var vm = new NewsViewModel
            {
                Categories = _db.NewsCategories.Select(c => c.Name),
                Category = category,
                NewsSources = _db.NewsSources.Select(ns => new NewsSourceViewModel {NewsSource = ns}).ToList(),
                HasFacebook = false
            };
            ODataQueryBuilder oDataQueryBuilder = ODataQueryBuilder.From("/odata/NewsItems")
                .Expand("NewsSource");
            switch (order)
            {
                case Order.NewestFirst:
                    oDataQueryBuilder.OrderBy("PubDate", ODataQueryBuilder.Order.desc);
                    break;
                case Order.AToZ:
                    oDataQueryBuilder.OrderBy("Title", ODataQueryBuilder.Order.asc);
                    break;
                case Order.ZToA:
                    oDataQueryBuilder.OrderBy("Title", ODataQueryBuilder.Order.desc);
                    break;
            }
            if (!category.IsNullOrWhiteSpace())
            {
                oDataQueryBuilder.FilterAndEq("CategoryName", category);
            }
            if (User.Identity.IsAuthenticated)
            {
                ApplicationUser user = _manager.FindById(User.Identity.GetUserId());
                foreach (int ns in user.IgnoredNewsSourcesIds)
                {
                    NewsSourceViewModel sourceView = vm.NewsSources.First(n => ns == n.NewsSource.Id);
                    sourceView.Ignored = true;
                    oDataQueryBuilder.FilterAnd("NewsSource/Id ne " + sourceView.NewsSource.Id);
                }
            }
            vm.OdataEndpoint = oDataQueryBuilder.Build();
            if (User.Identity.IsAuthenticated)
            {
                ApplicationUser user = _manager.FindById(User.Identity.GetUserId());
                foreach (int ns in user.IgnoredNewsSourcesIds)
                {
                    NewsSourceViewModel sourceView = vm.NewsSources.First(n => ns == n.NewsSource.Id);
                    sourceView.Ignored = true;
                }
                //if (category.IsNullOrWhiteSpace())
                //{
                //    RedirectResult redirect = GetFacebookLikes(vm);
                //    if (redirect != null)
                //        return redirect;
                //}
            }
            return View(vm);
        }

        //private RedirectResult GetFacebookLikes(NewsViewModel vm)
        //{
        //    //constant to get all user_likes that contain word news
        //    const string NEWS = "news";
        //    //constant to filter only the facebook links (not the photos)
        //    const string LINK = "link";

        //    //ACCESS TOKEN TO GET USER LIKES(facebook)/FOLLOWING(twitter) AND SEE NEWS POSTS
        //    var claimsIdentity = User.Identity as ClaimsIdentity;
        //    Claim claim = claimsIdentity.FindFirst("urn:facebook:access_token");
        //    string accessToken = claim != null ? claim.Value : null;
        //    if (accessToken != null)
        //    {
        //        vm.HasFacebook = true;
        //        try
        //        {
        //            var fb = new FacebookClient(accessToken);
        //            var likes = fb.Get<FacebookLikesCrate>("/me/likes?limit=1000");

        //            if (likes != null && likes.Data.Count != 0)
        //            {
        //                List<FacebookLikesModel> data = likes.Data;
        //                //category=Media/News/Publishing
        //                List<string> news =
        //                    data.Where(item => item.Category.Contains(NEWS)).Select(item2 => item2.ID).ToList();
        //                IEnumerable<FacebookPostsViewModel> captions = new List<FacebookPostsViewModel>();
        //                foreach (string str in news)
        //                {
        //                    var posts = fb.Get<FacebookPostsCrate>("/" + str + "/posts");
        //                    if (posts != null)
        //                    {
        //                        List<FacebookPostsViewModel> postsData = posts.Data;
        //                        string url;

        //                        FacebookPostsViewModel facebookPostsViewModel =
        //                            postsData.FirstOrDefault(
        //                                item =>
        //                                    item.Caption != null &&
        //                                    Uri.IsWellFormedUriString(item.Caption, UriKind.RelativeOrAbsolute));
        //                        if (facebookPostsViewModel == null)
        //                            continue;
        //                        url = facebookPostsViewModel.Caption;
        //                        captions = captions.Concat(postsData.Where(item => item.Type.Equals(LINK)));
        //                        //if (vm.NewsSources.Any(source =>
        //                        //{
        //                        //    string sourceUrl = source.NewsSource.SiteUrl;
        //                        //    var uri = new Uri(sourceUrl);
        //                        //    string uriWithoutScheme = uri.Host;
        //                        //    return //!source.Ignored &&
        //                        //           uriWithoutScheme.Equals(url, StringComparison.InvariantCultureIgnoreCase);
        //                        //}))
        //                        //{
        //                        //    captions = captions.Concat(postsData.Where(item => item.Type.Equals(LINK)));
        //                        //}
        //                    }
        //                }
        //                vm.FacebookPosts = captions;
        //            }
        //        }
        //        catch (FacebookOAuthException)
        //        {
        //            return Redirect("https://www.facebook.com/dialog/oauth?" +
        //                            "client_id=" + ConfigurationManager.AppSettings.Get("FacebookAppId") +
        //                            "&redirect_uri=" + Url.Action("Login", "Account", null,Request.Url.Scheme) +
        //                            "&scope=user_likes");
        //        }
        //    }
        //    return null;
        //}


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsBoard/Controllers/NewsSourcesController.cs
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using NewsBoard.Model;
using NewsBoard.Persistence;

namespace NewsBoard.Web.Controllers
{
    public class NewsSourcesController : Controller
    {
        private NewsDb db = new NewsDb();

        // GET: NewsSources
        public async Task<ActionResult> Index()
        {
            return View(await db.NewsSources.ToListAsync());
        }

        // GET: NewsSources/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsSource newsSource = await db.NewsSources.FindAsync(id);
            if (newsSource == null)
            {
                return HttpNotFound();
            }
            return View(newsSource);
        }

        // GET: NewsSources/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewsSources/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Name,RssUrl,FaviconUrl,SiteUrl")] NewsSource newsSource)
        {
            if (ModelState.IsValid)
            {
                db.NewsSources.Add(newsSource);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(newsSource);
        }

        // GET: NewsSources/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsSource newsSource = await db.NewsSources.FindAsync(id);
            if (newsSource == null)
            {
                return HttpNotFound();
            }
            return View(newsSource);
        }

        // POST: NewsSources/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,RssUrl,FaviconUrl,SiteUrl")] NewsSource newsSource)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newsSource).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(newsSource);
        }

        // GET: NewsSources/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsSource newsSource = await db.NewsSources.FindAsync(id);
            if (newsSource == null)
            {
                return HttpNotFound();
            }
            return View(newsSource);
        }

        // POST: NewsSources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NewsSource newsSource = await db.NewsSources.FindAsync(id);
            db.NewsSources.Remove(newsSource);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsBoard/Controllers/RequestNewsSourcesController.cs
using System.Linq;
using System.Web.Mvc;
using NewsBoard.Model;
using NewsBoard.Persistence;

namespace NewsBoard.Web.Controllers
{
    [Authorize]
    public class RequestNewsSourcesController : Controller
    {
        private NewsDb _db = new NewsDb();


        // GET: NewsSourcesRequest
        [Authorize(Roles = "admin")]
        public ActionResult Admin()
        {
            return View(_db.NewsSourceRequests);
        }

        public ActionResult Index(string q)
        {
            return View(model: q);
        }

        public ActionResult Request(NewsSourceRequest request)
        {
            string username = User.Identity.Name;
            bool find =
                _db.NewsSourceRequests.Any(
                    nsr => nsr.Requester == username && nsr.Name == request.Name);
            if (!find)
            {
                request.Requester = username;
                _db.NewsSourceRequests.Add(request);
                _db.SaveChanges();
            }
            return new EmptyResult();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsBoard/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin";
}

<h2 class="text-center">Admin area</h2>

<div class="row">
    <div class="col-md-offset-4 col-md-4 btn-group-vertical text-center">
        <a href="@Url.Action("Admin", "RequestNewsSources")" class="btn btn-lg btn-success">View requested news sources</a>
        <a href="@Url.Action("Index", "NewsSources")" class="btn btn-lg btn-danger">Edit rss sources</a>
        <a href="@Url.Action("Index", "NewsCategories")" class="btn btn-lg btn-warning">Edit categories</a>
        <a href="@Url.Action("News")" class="btn btn-lg btn-primary">Categorize news</a>
    </div>
</div>

NewsBoard/Views/Admin/News.cshtml
@using NewsBoard.Constants
@using NewsBoard.Model
@model NewsBoard.Web.ViewModels.AdminNewsViewModel

@{
    ViewBag.Title = "Manage News";
}

<div class="row">
    <div class="col-lg-4">
        <h3>@Model.Category News</h3>
        @foreach (NewsItem newsItem in Model.News)
        {
            <div class="thumbnail news-items">
                <div class="caption">
                    <a href="@newsItem.Link"><h3>@newsItem.Title</h3></a>
                    <p>@newsItem.Description</p>
                </div>
            </div>
            <p></p>
        }
    </div>
    <div class="col-lg-2">
        <div class="affix">
            <div class="row">
                <h3>Category</h3>
                <select class="form-control" id="categories" size="6">
                    @foreach (String cat in Model.NewsCategories)
                    {
                        <option value="@cat">@cat</option>
                    }
                </select>
            </div>
            <div class="row spacer text-center">
                <button id="categorize-btn" class="btn btn-primary">Categorize!</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="affix">
            <div class="row" data-bind="visible: hasSelectedNewsItem">
                <div class="row">
                    <h3>NewsItem Keywords(<span data-bind="text: words().length"></span>)</h3>
                    <input data-bind="value: newWord" type="text" placeholder="words" />
                    <button data-bind="click: addWord" type="button" class="btn btn-default">Add</button>
                </div>
                <div class="row spacer">
                    <select size="5" data-bind="options: words,  optionsText: $data, value: selectedWord, visible: words().length > 0"></select>
                    <button data-bind="click: removeWord" type="button" class="btn btn-default">Remove</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="affix">
            <div class="list-group spacer">
                <a class="list-group-item" @(Model.Category == Constants.DEFAULTMANUALCATEGORY ? "active" : "") href="@Url.Action("News", new {category = ""})">@Constants.DEFAULTMANUALCATEGORY</a>
                @foreach (string cat in Model.NewsCategories)
                {
                    <a class="list-group-item @(cat == Model.Category ? "active" : "")" href="@Url.Action("News", new {category = ""})/@cat">@cat</a>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="@Url.Content("~/Scripts/knockout-3.1.0.js")"></script>
    <script>
        function ViewModel() {
            var self = this;
            self.words = ko.observableArray();
            self.newWord = "";
            self.hasSelectedNewsItem = ko.observable(false);
            self.selectedWord = ko.observable();
            self.addWord = function() {
                var splitWords = self.newWord.split(' ');
                for (var i = 0; i < splitWords.length; ++i)
                    self.words.push(splitWords[i]);
            };

            self.removeWord = function() {
                self.words.remove(self.selectedWord());
            };

            self.reloadWords = function(valueSelected) {
                $.getJSON('@Url.Action("GetTopWords")', { newsitemId: valueSelected })
                    .done(function(data) {
                        self.words(data);
                    });
            };

        };

        var viewModel = new ViewModel();
        ko.applyBindings(viewModel);

        //EVENTS

        var selected = $(null);
        var selectedId;

        $('.news-items').click(function() {
            selected.css('background-color', '');
            $(this).css('background-color', '#00ff7f');
            selected = $(this);
            selectedId = $(this).find('a').attr('href');
            viewModel.reloadWords(selectedId);
            viewModel.hasSelectedNewsItem(true);
        });

        $('#categorize-btn').click(function() {

            var selectedCategory = $('#categories option:selected');
            if (!selectedId || selectedCategory.length === 0) return;
            $.post('@Url.Action("Categorize")',
            {
                category: selectedCategory.val(),
                newsitemId: selectedId,
                topwords: viewModel.words().join(' ')
            });
            viewModel.hasSelectedNewsItem(false);
            selected.remove();
        });
    </script>
}